theme: jekyll-theme-minimal
title: Khunires Knowledge Base
description: An open knowledge base toolkit plan for Blender and UPBGE. the first layer is atomic nodes of Blender 4.5 and UPBGE 0.44 that with application examples documented here, Shder editor and compositor editor are in the way. after this phase documentation of these nodes combinations as like as molecules would added a new layer functionality with tangible outcomes to our modular ecosystem.
